compute_environment: LOCAL_MACHINE                                                                                                                
debug: true                                                                                                                                       
deepspeed_config:
  deepspeed_config_file: configs/deepspeed.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: pytorch-workers-0-0.pytorch
main_process_port: 3389
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
