defaults:
  - _self_
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg: h100tp8mbs1.yaml

skip_evals: ${oc.decode:${oc.env:SKIP_EVAL,${floor:${add:${multiply:0.125,${model.global_batch_size}},2}}}}
load_ckpt: ${oc.decode:${oc.env:LOAD_CKPT,False}}
data_root: ${oc.decode:${oc.env:DATA_ROOT,/data}}
ckpt_root: ${oc.decode:${oc.env:CKPT_ROOT,/ckpt}}

trainer:
  devices: 8
  num_nodes: ${oc.decode:${oc.env:NODE_COUNT,1}}
  max_steps: 30
  val_check_interval: 200
  limit_val_batches: 5
model:
  num_layers: 80
  seed: 1234
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 1
  context_parallel_size: 1
  eval_cp: ${oc.decode:${oc.env:CP_EVAL,null}}
  global_batch_size: 1024
  micro_batch_size: 2
  val_micro_batch_size: ${oc.decode:${oc.env:VAL_MBS,null}}
  val_global_batch_size: ${floor_div:${multiply:${oc.decode:${oc.env:VAL_MBS,1}},${floor_div:${multiply:${trainer.devices},${trainer.num_nodes}},${multiply:${model.tensor_model_parallel_size},${model.pipeline_model_parallel_size}}}},${oc.decode:${oc.env:CP_EVAL,${oc.env:CP,1}}}}
  max_position_embeddings: 8192
  encoder_seq_length: 8192
  sequence_parallel: true
  ub_tp_comm_overlap: false

  ## Transformer Engine
  fp8: true
  fp8_params: true
  fp8_hybrid: true
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max
  reduce_amax: ${oc.decode:${oc.env:FP8_REDUCE_AMAX,False}}
  fp8_e4m3: true
  fp8_interval: 1
  fp8_margin: 0
  fp8_dot_product_attention: ${oc.decode:${oc.env:FP8_DPA,0}}
  cp_comm_type: ${oc.decode:${oc.env:CP_COMM_TYPE,'a2a'}}
  activation_func_fp8_input_store: ${oc.decode:${oc.env:FP8_ACT,0}}

  external_cuda_graph: ${oc.decode:${oc.env:LAYER_CUDA_GRAPH,False}}
  enable_cuda_graph: ${oc.decode:${oc.env:MCORE_CUDA_GRAPH,False}}
  use_te_rng_tracker: ${oc.decode:${oc.env:USE_TE_RNG_TRACKER,True}}
  enable_cg_fp8_weight_caching: ${oc.decode:${oc.env:CG_WEIGHT_CACHING,True}}

  cpu_offloading: ${oc.decode:${oc.env:CPU_OFFLOADING,False}}
  cpu_offloading_num_layers: ${oc.decode:${oc.env:CPU_OFFLOADING_NUM_LAYERS,20}}
  cpu_offloading_activations: True
  cpu_offloading_weights: False

  memory_profile:
    enabled: ${oc.decode:${oc.env:MEMORY_PROFILE,False}}
    start_step: 1
    end_step: 4
    rank: 0
    output_path: "/results/"

  custom:
    warmup: ${oc.decode:${oc.env:WARMUP,False}}
    warmup_train_steps: ${oc.decode:${oc.env:WARMUP_TRAIN_STEPS,5}}
    warmup_validation_steps: ${oc.decode:${oc.env:WARMUP_VALIDATION_STEPS,5}}
    reset_fp8_stats_after_warmup: ${oc.decode:${oc.env:RESET_FP8_STATS_AFTER_WARMUP,1}}

optim:
  lr: 0.00015
  use_distributed_optimizer: ${oc.decode:${oc.env:USE_DISTRIBUTED_OPTIMIZER,True}}
  overlap_param_gather_with_optimizer_step: ${oc.decode:${oc.env:OVERLAP_PARAM_GATHER_WITH_OPTIMIZER_STEP,False}}
  sched:
    warmup_steps: 2000

ddp:
  overlap_grad_reduce: ${oc.decode:${oc.env:DDP_OVERLAP_GRAD_REDUCE,False}}
  overlap_param_gather: ${oc.decode:${oc.env:DDP_OVERLAP_PARAM_GATHER,False}}
  fp8_param_gather: ${oc.decode:${oc.env:DDP_FP8_PARAM_GATHER,False}}
  average_in_collective: ${oc.decode:${oc.env:DDP_AVERAGE_IN_COLLECTIVE,False}}
